Parameters:
  EnvironmentName:
    Description: Environment Name
    Type: String
    AllowedValues: [ development, production ]
    ConstraintDescription: Must be development or production

Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0ed9277fb7eb570c9
    us-east-2:
      HVM64: ami-002068ed284fb165b
    us-west-1:
      HVM64: ami-03af6a70ccd8cb578
    us-west-2:
      HVM64: ami-00f7e5c52c0f43726
  
  EnvironmentToInstanceType:
    development:
      instanceType: t2.micro
    production:
      instanceType: t2.small

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref EnvironmentName, instanceType]
      ImageId: !FindInMap [ AWSRegionArch2AMI, !Ref 'AWS::Region', HVM64 ]
