Parameters:
  VPCId:
    Description: VPC to create the SG
    Type: AWS::EC2::VPC::Id

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Test Drift SSH Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 10.0.0.0/25
          FromPort: 22
          ToPort: 22
      VpcId: !Ref VPCId
  
  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Test Drift HTTP SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
      VpcId: !Ref VPCId