Parameters:
  ApplicationName:
    Description: The application name
    Type: String
  VPCId: 
    Description: VPC to create SG
    Type: AWS::EC2::VPC::Id

Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Security Group for ${ApplicationName}
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 10.0.0.0/25
          FromPort: 22
          ToPort: 22
          Description: SSH for Enginnering Team
        - IpProtocol: tcp
          CidrIp: 192.168.0.0/25
          FromPort: 22
          ToPort: 22
          Description: SSH for HR Team
        - IpProtocol: tcp
          CidrIp: 176.16.0.0/31
          FromPort: 22
          ToPort: 22
          Description: SSH for Business Team
      VpcId: !Ref VPCId

Outputs:
  SSHGroupId:
    Value: !Ref SSHSecurityGroup
    Description: Id for the SSH Security Group

      